name = "MiniWalnut"
version = "0.1.0"
defaultTargets = ["miniwalnut"]

[[lean_lib]]
name = "MiniWalnut"

[[lean_exe]]
name = "miniwalnut"
root = "Main"

[[require]]
scope = "leanprover"
name = "doc-gen4"
rev = "main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
